[build]
  command = "curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.12/mdbook-v0.4.12-x86_64-unknown-linux-gnu.tar.gz | tar xvz -C /tmp/ && cd docs && /tmp/mdbook build"
  publish = "docs/book"
